<?php

return [
    'permissions' => [
        'admin.dashboard',
        'admin.manage_admins',
        'admin.manage_roles',
        'admin.manage_employers',
        'admin.manage_candidates',
        'admin.manage_jobs',
        'admin.manage_references',
        'admin.manage_consultations',
        'admin.manage_blogs',
        'admin.manage_faqs',
        'admin.manage_inquiries',
        'admin.manage_legal_pages',
        'admin.manage_cms_pages',
        'admin.manage_subscribers',
        'admin.manage_notices',
        'admin.send_bulk_email',
        'admin.manage_ads',
        'admin.manage_plans',
        'admin.manage_transactions',
        'admin.manage_front_settings',
        'admin.manage_settings',
        'admin.manage_notification_settings',
        'admin.manage_email_templates',
    ],

    // A regular Admin receives operational access. Sensitive user and system
    // administration remains exclusive to the Super Admin by default.
    'admin_permissions' => [
        'admin.dashboard',
        'admin.manage_employers',
        'admin.manage_candidates',
        'admin.manage_jobs',
        'admin.manage_references',
        'admin.manage_consultations',
        'admin.manage_blogs',
        'admin.manage_faqs',
        'admin.manage_inquiries',
        'admin.manage_legal_pages',
        'admin.manage_cms_pages',
        'admin.manage_subscribers',
        'admin.manage_notices',
        'admin.send_bulk_email',
        'admin.manage_ads',
        'admin.manage_plans',
        'admin.manage_transactions',
    ],

    'route_groups' => [
        'admin.dashboard' => [
            'dashboard*', 'dashboard-chart-data*', 'profile', 'profile-update', 'change-password',
        ],
        'admin.manage_admins' => ['admins*'],
        'admin.manage_roles' => ['roles-permissions*'],
        'admin.manage_employers' => ['employers*', 'reported-employers*'],
        'admin.manage_candidates' => [
            'candidates*', 'candidates-export-excel*', 'resumes*', 'delete-resumes*',
            'reported-candidates*', 'selected-candidates*',
        ],
        'admin.manage_jobs' => [
            'jobs*', 'government-jobs*', 'pending-jobs*', 'pending-jobs-add-reason*',
            'pending-jobs-change-status*', 'reported-jobs*', 'expired-jobs*',
            'expire-in-7-days*', 'job-notifications*', 'employer-jobs*',
        ],
        'admin.manage_consultations' => ['consultation-leads*'],
        'admin.manage_blogs' => ['post-categories*', 'posts*', 'post-comments*'],
        'admin.manage_faqs' => ['faqs*', 'faq-categories*'],
        'admin.manage_inquiries' => ['inquires*'],
        'admin.manage_legal_pages' => ['privacy-policy*', 'terms-conditions*'],
        'admin.manage_cms_pages' => ['cms-services*', 'cms-about-us*'],
        'admin.manage_subscribers' => ['subscribers*'],
        'admin.manage_notices' => ['noticeboards*'],
        'admin.send_bulk_email' => ['bulk-email*'],
        'admin.manage_ads' => ['ads*', 'media*'],
        'admin.manage_plans' => ['plans*'],
        'admin.manage_transactions' => ['transactions*', 'invoices*', 'change-transaction-status*'],
        'admin.manage_front_settings' => ['front-settings*'],
        'admin.manage_settings' => ['settings*', 'logs*'],
        'admin.manage_notification_settings' => ['notification-settings*'],
        'admin.manage_email_templates' => ['email-template*'],
        'admin.manage_references' => [
            'profile-references*', 'job-categories*', 'job-types*', 'job-tags*', 'job-shifts*',
            'job-workplaces*', 'job-employment-statuses*', 'job-experience-units*',
            'job-gender-preferences*', 'company-sizes*', 'company-categories*', 'skills*',
            'skill-learning-sources*', 'industries*', 'functional-areas*', 'career-levels*',
            'salary-currencies*', 'salary-periods*', 'ownership-types*', 'degree-levels*',
            'education-degree-titles*', 'education-major-groups*', 'education-boards*',
            'education-results*', 'countries*', 'states*', 'divisions*', 'cities*',
            'districts*', 'city-villages*', 'thanas*', 'genders*', 'languages*',
            'language-proficiencies*', 'online-profile-platforms*', 'marital-status*',
            'candidate-religions*', 'blood-groups*', 'disability-difficulties*',
            'candidate-reference-relations*', 'employer-reference-relations*',
            'employer-disability-facilities*', 'army-ba-no-prefixes*', 'army-ranks*',
            'army-employment-types*', 'army-arms*', 'consultation-types*',
            'consultation-contact-methods*',
        ],
    ],
];
